---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  apikey: Add your base64 encoded apikey from https://financialmodelingprep.com/login
  password: Add your base64 encoded gmail account password

